create table if not exists public.i_raw_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_name text not null references public.i_banks(bank_name),
  sender_name text not null,
  raw_message text not null,
  created_at timestamptz not null default now(),
  unique (user_id, sender_name, raw_message)
);

alter table public.i_raw_data enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'i_raw_data'
      and policyname = 'i_raw_data_own_rows'
  ) then
    create policy "i_raw_data_own_rows"
    on public.i_raw_data for all
    to authenticated
    using (user_id = auth.uid())
    with check (
      user_id = auth.uid()
      and exists (
        select 1 from public.i_banks b
        where b.bank_name = i_raw_data.bank_name
      )
    );
  end if;
end
$$;

grant all on public.i_raw_data to authenticated;
grant usage, select on all sequences in schema public to authenticated;
