begin;

alter table public.i_transactions
add column if not exists bank_name text;

update public.i_transactions t
set bank_name = b.name
from public.i_banks b
where t.bank_name is null
  and t.bank_id = b.id;

drop table if exists public.i_banks_new cascade;

create table public.i_banks_new (
  id bigint generated by default as identity primary key,
  bank_name text not null unique
);

insert into public.i_banks_new (bank_name)
select distinct trim(name)
from public.i_banks
where nullif(trim(name), '') is not null
union
select distinct trim(bank_name)
from public.i_transactions
where nullif(trim(bank_name), '') is not null;

alter table public.i_transactions
drop constraint if exists i_transactions_bank_id_fkey;

alter table public.i_transactions
alter column bank_name set not null;

alter table public.i_transactions
add constraint i_transactions_bank_name_fkey
foreign key (bank_name) references public.i_banks_new(bank_name);

alter table public.i_transactions
drop column if exists bank_id;

drop policy if exists "i_transactions_own_rows" on public.i_transactions;

drop policy if exists "i_banks_own_rows" on public.i_banks;
drop policy if exists "i_banks_read_all" on public.i_banks;
drop policy if exists "i_banks_write_all" on public.i_banks;
drop table public.i_banks;

alter table public.i_banks_new rename to i_banks;
alter table public.i_banks enable row level security;

create policy "i_banks_read_all"
on public.i_banks for select
to authenticated
using (true);

create policy "i_banks_write_all"
on public.i_banks for all
to authenticated
using (true)
with check (nullif(trim(bank_name), '') is not null);

create policy "i_transactions_own_rows"
on public.i_transactions for all
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.i_banks b
    where b.bank_name = i_transactions.bank_name
  )
);

grant all on public.i_banks to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
