-- Secure per-user schema for Supabase (RLS + Auth)
-- This matches the app's PostgREST calls:
-- - public.i_users (id = auth.users.id + mirrored profile fields)
-- - public.i_banks (id, bank_name) shared catalog
-- - public.i_transactions primary key (user_id, id)
--
-- WARNING: This will DROP existing tables + data.

drop table if exists public.i_transactions cascade;
drop table if exists public.i_raw_data cascade;
drop table if exists public.i_banks cascade;
drop table if exists public.i_users cascade;
drop trigger if exists on_auth_user_changed_sync_i_users on auth.users;
drop function if exists public.sync_auth_user_to_i_users();

create table public.i_users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  account_created_at timestamptz,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.sync_auth_user_to_i_users()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.i_users (
    id,
    name,
    email,
    account_created_at,
    last_sign_in_at,
    updated_at
  )
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'name', ''),
      nullif(new.raw_user_meta_data ->> 'full_name', '')
    ),
    new.email,
    new.created_at,
    new.last_sign_in_at,
    now()
  )
  on conflict (id) do update
  set
    name = excluded.name,
    email = excluded.email,
    account_created_at = excluded.account_created_at,
    last_sign_in_at = excluded.last_sign_in_at,
    updated_at = now();

  return new;
end;
$$;

create trigger on_auth_user_changed_sync_i_users
after insert or update of email, raw_user_meta_data, last_sign_in_at
on auth.users
for each row
execute function public.sync_auth_user_to_i_users();

alter table public.i_users enable row level security;

create policy "i_users_select_own"
on public.i_users for select
to authenticated
using (id = auth.uid());

create policy "i_users_insert_own"
on public.i_users for insert
to authenticated
with check (id = auth.uid());

create policy "i_users_update_own"
on public.i_users for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create table public.i_banks (
  id bigint generated by default as identity primary key,
  bank_name text not null unique
);

alter table public.i_banks enable row level security;

create policy "i_banks_read_all"
on public.i_banks for select
to authenticated
using (true);

create policy "i_banks_write_all"
on public.i_banks for all
to authenticated
using (true)
with check (nullif(trim(bank_name), '') is not null);

create table public.i_transactions (
  id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_name text not null references public.i_banks(bank_name),
  occurred_at timestamptz not null,
  sender text not null,
  type text not null,
  category text,
  amount double precision not null,
  balance double precision,
  counterparty text,
  ref_num text,
  total_charged double precision,
  recipt_link text,
  raw_body text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, id)
);

alter table public.i_transactions enable row level security;

create policy "i_transactions_own_rows"
on public.i_transactions for all
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.i_banks b
    where b.bank_name = i_transactions.bank_name
  )
);

create table public.i_raw_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bank_name text not null references public.i_banks(bank_name),
  sender_name text not null,
  raw_message text not null,
  created_at timestamptz not null default now(),
  unique (user_id, sender_name, raw_message)
);

alter table public.i_raw_data enable row level security;

create policy "i_raw_data_own_rows"
on public.i_raw_data for all
to authenticated
using (user_id = auth.uid())
with check (
  user_id = auth.uid()
  and exists (
    select 1 from public.i_banks b
    where b.bank_name = i_raw_data.bank_name
  )
);

grant all on public.i_users, public.i_banks, public.i_transactions, public.i_raw_data to authenticated;
grant usage, select on all sequences in schema public to authenticated;
